### ISSUE TITLE
[Suggestion] Add a GUID generator

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/LeoCorpLibrary#124]
**Suggestion:**
Add a GUID generator.

**Describe the solution:**
Add a GUID generator that can:
- [x] Generate a GUID
- [x] Generate a GUID from string
- [x] Generate a GUID of a specific lenght
- [x] Generate a GUID with(out) a hyphen
- [x] Generate a GUID with(out) braces
- [x] Generate a GUID in upper/lower case
