### ISSUE TITLE
[Enhancement] Add the possibility to convert an `int` size (kb, mb) to another size (gb...)

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/LeoCorpLibrary#205]
**Enhancement:**
Add the possibility to convert an `int` size (kb, mb) to another size (gb...).

**Describe the solution:**
Add an extension method:

- [x] Add the possibility to convert a size unit to byte
- [x] Add the possibility to convert a size unit to kilobyte
- [x] Add the possibility to convert a size unit to megabyte
- [x] Add the possibility to convert a size unit to gigabyte
- [x] Add the possibility to convert a size unit to terabyte
- [x] Add the possibility to convert a size unit to petabyte
