### ISSUE TITLE
[Documentation] Update documentation

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/LeoCorpLibrary#251]
### What is the problem?

- [x] Update documentation
- [x] Update XML documentation
- [x] Update README links to new documentation website
- [x] Add message to old documentation in GitHub Wiki.
