### ISSUE TITLE
[Documentation] Mettre à jour la documentation

### ISSUE THREAD

**Issue by Leo-Corporation** [Leo-Corporation/LeoCorpLibrary#84]
**Description du problème :**
- [x] Mettre à jour la documentation
- [x] Mettre à jour le README
   - [x] Mettre à jour le changelog
   - [x] Ajouter une liste des branches
   - [x] Ajouter des badges (build passing)
- [x] Mettre à jour la documentation XML
